---
language: python
python: "2.7"

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/

install:
  - pip install ansible

script:
  # Check syntax
  - ansible-playbook -i "localhost," test.yml --syntax-check

  # First run
  - ansible-playbook -i "localhost," -c local test.yml

  # Second run
  - >
    ansible-playbook -i "localhost," -c local test.yml
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)
